[CLI] Add support for preparing GB patch releases
wordpress-mobile/release-toolkit-gutenberg-mobile pull request #212
Opened 2023-11-02 20:57 UTC by jhnstn

This updates the `prepare gb` command to accept patch versions (e.g. 1.1071) and a `prs` flag to pass a comma separated list of PRs on gutenberg 

If the command recognizes a patch release it will branch of the prior release and then attempt cherry pick the merge commits from the passed in PRs.

If there is a merge commit the script will prompt to resolve the merge commit in the users default `$EDITOR`. if `EDITOR` is not set, the script will prompt for a command to open the conflicting files (e.g. `vim` or `code` )

Once the branch is prepared the script will prompt to edit the changelog since the changelog might not accurately reflect the changes in the patch.

## Testing
This is difficult to completely verify with out getting noisy on the Gutenberg repo. Also this is difficult to set up on forked repos. I suggest using the `WordPress/gutenberg` to test but just make sure to exit the script when prompted to create the pr i.e. a this prompt "**Ready to create the PR on WordPress/gutenberg? [y/n]**"

I also found it is easier to verify the scripts correctness by trying to recreate existing patch releases.

### Testing with merge conflicts

- Run `GBM_WORDPRESS_ORG=WordPress  go run main.go release prepare gb 1.103.2 --no-tag --prs=54281 ` to recreate the `1.103.2` release (use the --no-tag just in case the PR does get created)
- Follow the prompts to resolve any merge conflicts
- Follow the prompts to correctly update the CHANGELOG
- Note the commits to be included in the PR when the preview is presented
- Exit the script without creating the PR

### Testing with multiple PRs
- Run `GBM_WORDPRESS_ORG=WordPress  go run main.go release prepare gb 1.103.2 --no-tag --prs=54281,54096`
- Follow the same prompts as above but you should get two merge conflicts
- Note that both PR commits are listed in the commits in the PR list
- Exit the script without creating the PR

### Verifying the branching (also test with out merge conflicts)
- Run `GBM_WORDPRESS_ORG=WordPress  go run main.go release prepare gb 1.107.1 --prs=55613 --no-tag --keep`
- Note that the only prompt is to verify the change log (as of the time of this pr creation, the could change)
- Exit the script without creating the PR
- `cd` into the temporary directory
- Run `git reflog`
- Note that the log history starts on a grafted branch at the tag `rnmobile/1.107.0`
It should look something like :
```reflog
d6311ae (HEAD -> rnmobile/release_1.107.1) HEAD@{0}: commit: Release script: Update podfile
6451ed7 HEAD@{1}: reset: moving to HEAD
6451ed7 HEAD@{2}: commit: Release script: Update CHANGELOG for version 1.107.1
b7c4eb7 HEAD@{3}: commit: Release script: Update react-native-editor version to 1.107.1
f84d2b8 HEAD@{4}: cherry-pick: [RNMobile] Fix error when pasting deeply nested structure content (#55613)
1c3a1ac (grafted, tag: rnmobile/1.107.0) HEAD@{5}: checkout: moving from 1c3a1ac5b7add6ed335787e9770dc59b0c9d8d6b to rnmobile/release_1.107.1
1c3a1ac (grafted, tag: rnmobile/1.107.0) HEAD@{6}: clone: from github.com:WordPress/gutenberg
```

### Testing the editor prompt
- Run `EDITOR= GBM_WORDPRESS_ORG=WordPress  go run main.go release prepare gb 1.107.1 --prs=55613 --no-tag` to nil out `$EDITOR`
- Note the prompt to provide a command to open the change log
- Try using any text editor that can open files from the command line e.g. `vim`, `code` or `nano`
- Note that the correct file from the temp directory is opened in the chosen editor

**Note** : There is no verification that a merge conflict was correctly resolved. I suspect most conflicts will be in the change notes so the last verification step should surface any issues with that file.

**Note**: The editor prompts have only been tested with `vim`,`code` and `nano` but in theory any command that takes a list of files should work.

2023-11-03 00:48 UTC, derekblank requested changes
Looks good! I was able to run through all of the patch scenarios successfully. I think I encountered a regression with the `prepare all` command, however:

```
➜ yes | GBM_WPMOBILE_ORG=derekblank GBM_WORDPRESS_ORG=derekblank go run main.go release prepare all 1.110.0
[INFO] Preparing Gutenberg for release 1.110.0
[INFO] Cloning Gutenberg to /var/folders/xk/xmtl5xjx33v_bp94749wm0j00000gn/T/gbm-2609010841/gb
Cloning into '.'...
warning: Could not find remote branch  to clone.
fatal: Remote branch  not found in upstream origin
[ERROR] error cloning the Gutenberg repository: exit status 128
```

This happens on both the main repos and my forked repos. I think this _might_ be coming from ` build.Base.Ref`. Is `prepare all` still a command, or should we run them individually as `gb` and `gbm`? If we're running them individually, we should remove `all` and update the docs.

2023-11-03 13:02 UTC, jhnstn commented
> Looks good! I was able to run through all of the patch scenarios successfully. I think I encountered a regression with the `prepare all` command, however:
> 
> ```
> ➜ yes | GBM_WPMOBILE_ORG=derekblank GBM_WORDPRESS_ORG=derekblank go run main.go release prepare all 1.110.0
> [INFO] Preparing Gutenberg for release 1.110.0
> [INFO] Cloning Gutenberg to /var/folders/xk/xmtl5xjx33v_bp94749wm0j00000gn/T/gbm-2609010841/gb
> Cloning into '.'...
> warning: Could not find remote branch  to clone.
> fatal: Remote branch  not found in upstream origin
> [ERROR] error cloning the Gutenberg repository: exit status 128
> ```
> 
> This happens on both the main repos and my forked repos. I think this _might_ be coming from ` build.Base.Ref`. Is `prepare all` still a command, or should we run them individually as `gb` and `gbm`? If we're running them individually, we should remove `all` and update the docs.

Ah thanks for checking that @derekblank ! I forgot to update the all command. I can push a fix.

2023-11-03 14:44 UTC, jhnstn commented
@derekblank I fixed the regression in https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/212/commits/696857cbc0f2f1859b26ebb875da6acdde82abad

2023-11-05 23:59 UTC, derekblank approved these changes
`prepare all` is working now. LGTM! 🚀

2023-11-05 23:59 UTC, merged